"""
flux2tiny — Custom pipeline that replaces Qwen3-4B with MiniCPM5-1B + adapter.

This module wraps diffusers' official Flux2KleinPipeline, feeding it prompt_embeds
generated by MiniCPM5-1B + trained projection adapter.
"""

from pathlib import Path
from typing import Optional
import torch
from PIL import Image
from diffusers import Flux2KleinPipeline, AutoencoderKLFlux2


class Flux2TinyPipeline:
    """
    FLUX.2-klein-4B image generation pipeline with MiniCPM5-1B as text encoder.

    Architecture:
      Text prompt → MiniCPM5-1B tokenizer → MiniCPM5-1B (frozen)
        → extract 3 hidden layers → projection adapter (trained)
        → [B, seq, 7680] prompt_embeds
        → Flux2KleinPipeline (official diffusers pipeline) → PIL Image
    """

    def __init__(
        self,
        flux_model_id: str = "black-forest-labs/FLUX.2-klein-4B",
        vae_model_id: str = "black-forest-labs/FLUX.2-small-decoder",
        student_model_id: str = "openbmb/MiniCPM5-1B",
        adapter_path: str = "adapter_checkpoints/adapter_best.safetensors",
        lora_path: str | None = "lora_checkpoints/final/transformer_lora",
        adapter_type: str = "per_layer",
        student_extract_layers: list[int] = [5, 12, 19],
        device: str = "cuda",
        dtype: torch.dtype = torch.bfloat16,
        cpu_offload: bool = True,
    ):
        self.device = torch.device(device)
        self.dtype = dtype
        self.student_extract_layers = student_extract_layers
        self.cpu_offload = cpu_offload

        print("=== Loading flux2tiny pipeline ===")
        self._load_student_encoder(student_model_id)
        self._load_adapter(adapter_path, adapter_type)
        self._load_flux_pipeline(flux_model_id, vae_model_id, lora_path=lora_path)
        print("=== Pipeline ready ===")

    def _load_student_encoder(self, model_id: str):
        """Load MiniCPM5-1B as text encoder."""
        print(f"Loading text encoder: {model_id}...")
        from transformers import AutoModelForCausalLM, AutoTokenizer

        self.tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        self.text_encoder = AutoModelForCausalLM.from_pretrained(
            model_id,
            torch_dtype=self.dtype,
            trust_remote_code=True,
        )
        self.text_encoder.eval()
        for p in self.text_encoder.parameters():
            p.requires_grad = False

        if self.cpu_offload:
            self.text_encoder = self.text_encoder.to("cpu")
            self._text_encoder_device = torch.device("cpu")
        else:
            self.text_encoder = self.text_encoder.to(self.device)
            self._text_encoder_device = self.device

        params = sum(p.numel() for p in self.text_encoder.parameters())
        print(f"  Text encoder: {params / 1e6:.1f}M params on {self._text_encoder_device}")

    def _load_adapter(self, adapter_path: str, adapter_type: str):
        """Load trained projection adapter."""
        from adapter import load_adapter
        print(f"Loading adapter: {adapter_path}...")
        self.adapter = load_adapter(
            adapter_path,
            adapter_type=adapter_type,
            source_dim=1536,   # MiniCPM5-1B hidden_size
            target_dim=2560,   # Qwen3-4B hidden_size (per layer)
            num_layers=3,
            device=str(self.device),
            dtype=self.dtype,
        )

    def _load_flux_pipeline(self, flux_model_id: str, vae_model_id: str, lora_path: str | None = None):
        """Load official FLUX.2 Klein pipeline without Qwen3 text encoder."""
        print(f"Loading FLUX.2 pipeline...")
        vae = AutoencoderKLFlux2.from_pretrained(vae_model_id, torch_dtype=self.dtype)
        self.pipe = Flux2KleinPipeline.from_pretrained(
            flux_model_id,
            vae=vae,
            text_encoder=None,
            tokenizer=None,
            torch_dtype=self.dtype,
        )
        if lora_path and Path(lora_path).exists():
            from peft import PeftModel
            print(f"Loading transformer LoRA weights from {lora_path}...")
            self.pipe.transformer = PeftModel.from_pretrained(
                self.pipe.transformer, lora_path
            )
        if self.cpu_offload:
            self.pipe.enable_model_cpu_offload()

    def encode_prompt(
        self,
        prompt: str | list[str],
        max_length: int = 128,
    ) -> torch.Tensor:
        """
        Encode text prompt(s) through MiniCPM5-1B + adapter.

        Returns prompt_embeds of shape [batch, seq_len, 7680].
        """
        if isinstance(prompt, str):
            prompt = [prompt]

        inputs = self.tokenizer(
            prompt,
            return_tensors="pt",
            padding="max_length",
            truncation=True,
            max_length=max_length,
        ).to(self._text_encoder_device)

        with torch.no_grad():
            outputs = self.text_encoder(
                **inputs,
                output_hidden_states=True,
                return_dict=True,
            )

        hidden_states_list = []
        for layer_idx in self.student_extract_layers:
            hs = outputs.hidden_states[layer_idx + 1]
            hs = hs.to(device=self.device, dtype=self.dtype)
            hidden_states_list.append(hs)

        with torch.no_grad():
            encoder_hidden_states = self.adapter(hidden_states_list)

        return encoder_hidden_states

    @torch.no_grad()
    def __call__(
        self,
        prompt: str,
        height: int = 1024,
        width: int = 1024,
        num_inference_steps: int = 4,
        guidance_scale: float = 1.0,
        generator: Optional[torch.Generator] = None,
        max_seq_len: int = 128,
    ) -> Image.Image:
        """Generate an image from a text prompt using official Flux2KleinPipeline."""
        prompt_embeds = self.encode_prompt(prompt, max_length=max_seq_len)

        output = self.pipe(
            prompt=None,
            prompt_embeds=prompt_embeds,
            height=height,
            width=width,
            num_inference_steps=num_inference_steps,
            guidance_scale=guidance_scale,
            generator=generator,
        )
        return output.images[0]
