"""
flux2tiny — Custom pipeline that replaces Qwen3-4B with a student text encoder + adapter.

This module wraps diffusers' official Flux2KleinPipeline, feeding it prompt_embeds
generated by student text encoder (MiniCPM5-1B, Qwen3.5-0.8B, etc.) + trained projection adapter.
"""

from pathlib import Path
from typing import Optional, Union
import torch
from PIL import Image
from diffusers import Flux2KleinPipeline, AutoencoderKLFlux2

from config import get_student_config, StudentConfig


class Flux2TinyPipeline:
    """
    FLUX.2-klein-4B image generation pipeline with student text encoder.

    Architecture:
      Text prompt → Student tokenizer → Student model (frozen)
        → extract hidden layers → projection adapter (trained)
        → [B, seq, 7680] prompt_embeds
        → Flux2KleinPipeline (official diffusers pipeline) → PIL Image
    """

    def __init__(
        self,
        config: Union[str, StudentConfig] = "minicpm-1b",
        flux_model_id: Optional[str] = None,
        vae_model_id: Optional[str] = None,
        student_model_id: Optional[str] = None,
        adapter_path: Optional[str] = None,
        lora_path: Optional[str] = None,
        adapter_type: str = "per_layer",
        device: str = "cuda",
        dtype: torch.dtype = torch.bfloat16,
        cpu_offload: bool = True,
    ):
        if isinstance(config, str):
            self.student_config = get_student_config(config)
        else:
            self.student_config = config

        self.device = torch.device(device)
        self.dtype = dtype
        self.cpu_offload = cpu_offload

        flux_model_id = flux_model_id or self.student_config.teacher_model_id
        vae_model_id = vae_model_id or self.student_config.vae_model_id
        student_model_id = student_model_id or self.student_config.student_model_id

        if adapter_path is None:
            adapter_path = self.student_config.get_adapter_path("adapter_best.safetensors")
            if not Path(adapter_path).exists():
                adapter_path = self.student_config.get_adapter_path("adapter_final.safetensors")

        if lora_path is None:
            lora_path = self.student_config.get_lora_path("final/transformer_lora")

        self.student_extract_layers = self.student_config.extract_layers

        print(f"=== Loading flux2tiny pipeline (preset: {self.student_config.name}) ===")
        self._load_student_encoder(student_model_id)
        self._load_adapter(adapter_path, adapter_type)
        self._load_flux_pipeline(flux_model_id, vae_model_id, lora_path=lora_path)
        print("=== Pipeline ready ===")

    def _load_student_encoder(self, model_id: str):
        """Load student text encoder."""
        print(f"Loading text encoder: {model_id}...")
        from transformers import AutoModelForCausalLM, AutoTokenizer

        self.tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        self.text_encoder = AutoModelForCausalLM.from_pretrained(
            model_id,
            torch_dtype=self.dtype,
            trust_remote_code=True,
        )
        self.text_encoder.eval()
        for p in self.text_encoder.parameters():
            p.requires_grad = False

        if self.cpu_offload:
            self.text_encoder = self.text_encoder.to("cpu")
            self._text_encoder_device = torch.device("cpu")
        else:
            self.text_encoder = self.text_encoder.to(self.device)
            self._text_encoder_device = self.device

        params = sum(p.numel() for p in self.text_encoder.parameters())
        print(f"  Text encoder: {params / 1e6:.1f}M params on {self._text_encoder_device}")

    def _load_adapter(self, adapter_path: str, adapter_type: str):
        """Load trained projection adapter."""
        from adapter import load_adapter
        print(f"Loading adapter: {adapter_path}...")
        self.adapter = load_adapter(
            adapter_path,
            adapter_type=adapter_type,
            source_dim=self.student_config.hidden_size,
            target_dim=self.student_config.teacher_hidden_size,
            num_layers=self.student_config.num_layers,
            device=str(self.device),
            dtype=self.dtype,
        )

    def _load_flux_pipeline(self, flux_model_id: str, vae_model_id: str, lora_path: Optional[str] = None):
        """Load official FLUX.2 Klein pipeline without Qwen3 text encoder."""
        print(f"Loading FLUX.2 pipeline...")
        vae = AutoencoderKLFlux2.from_pretrained(vae_model_id, torch_dtype=self.dtype)
        self.pipe = Flux2KleinPipeline.from_pretrained(
            flux_model_id,
            vae=vae,
            text_encoder=None,
            tokenizer=None,
            torch_dtype=self.dtype,
        )
        if lora_path and Path(lora_path).exists():
            from peft import PeftModel
            print(f"Loading transformer LoRA weights from {lora_path}...")
            self.pipe.transformer = PeftModel.from_pretrained(
                self.pipe.transformer, lora_path
            )
        if self.cpu_offload:
            self.pipe.enable_model_cpu_offload()

    def encode_prompt(
        self,
        prompt: Union[str, list[str]],
        max_length: int = 128,
    ) -> torch.Tensor:
        """
        Encode text prompt(s) through student encoder + adapter.

        Returns prompt_embeds of shape [batch, seq_len, 7680].
        """
        if isinstance(prompt, str):
            prompt = [prompt]

        inputs = self.tokenizer(
            prompt,
            return_tensors="pt",
            padding="max_length",
            truncation=True,
            max_length=max_length,
        ).to(self._text_encoder_device)

        with torch.no_grad():
            outputs = self.text_encoder(
                **inputs,
                output_hidden_states=True,
                return_dict=True,
            )

        hidden_states_list = []
        for layer_idx in self.student_extract_layers:
            hs = outputs.hidden_states[layer_idx + 1]
            hs = hs.to(device=self.device, dtype=self.dtype)
            hidden_states_list.append(hs)

        with torch.no_grad():
            encoder_hidden_states = self.adapter(hidden_states_list)

        return encoder_hidden_states

    @torch.no_grad()
    def __call__(
        self,
        prompt: str,
        height: int = 1024,
        width: int = 1024,
        num_inference_steps: int = 4,
        guidance_scale: float = 1.0,
        generator: Optional[torch.Generator] = None,
        max_seq_len: int = 128,
    ) -> Image.Image:
        """Generate an image from a text prompt using official Flux2KleinPipeline."""
        prompt_embeds = self.encode_prompt(prompt, max_length=max_seq_len)

        output = self.pipe(
            prompt=None,
            prompt_embeds=prompt_embeds,
            height=height,
            width=width,
            num_inference_steps=num_inference_steps,
            guidance_scale=guidance_scale,
            generator=generator,
        )
        return output.images[0]
